variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'
- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    publishWebProjects: true
- task: AzureWebApp@1
  inputs:
    azureSubscription: 'MSFT Visual Studio(677b9361-696b-426b-a712-976620de9736)'
    appType: 'webAppLinux'
    appName: 'dotnetwebapp'
    package: '$(System.DefaultWorkingDirectory)/**/*.zip'

  
- task: AzureRmWebAppDeployment@4
  inputs:
    VirtualApplication: 'dotnetwebapp'
